### ISSUE TITLE
hide one more exception for screenshot generation

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1030]
we can't generate screenshot if no window exists.
Let's catch this exception and produce just a warning in the log.

stacktrace:
_2020-05-20 21:17:38 Screenshot [TestNG-tests-2-23] [ERROR] Unable to capture screenshot due to the Exception!
java.lang.RuntimeException: org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=83.0.4103.61)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-10-199-2-222', ip: '10.199.1.43', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-1105-aws', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 83.0.4103.61, chrome: {chromedriverVersion: 83.0.4103.39 (ccbf011cb2d2b..., userDataDir: /tmp/.com.google.Chrome.gcoIP4}, goog:chromeOptions: {debuggerAddress: localhost:34990}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(manual, http=10.199.1..., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 762e8c3d609a1f355f69db5ae72cd79f8c15e2a722b739b8f4e606aff2f5949f
	at ru.yandex.qatools.ashot.util.InnerScript.execute(InnerScript.java:29)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getFullHeight(ViewportPastingDecorator.java:67)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:41)
	at ru.yandex.qatools.ashot.shooting.ViewportPastingDecorator.getScreenshot(ViewportPastingDecorator.java:35)
	at ru.yandex.qatools.ashot.AShot.takeScreenshot(AShot.java:143)
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.takeFullScreenshot(Screenshot.java:561)
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.capture(Screenshot.java:438)
	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.captureFailure(Screenshot.java:156)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.takeScreenshot(CarinaListener.java:808)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onTestFailure(CarinaListener.java:277)
	at com.nordstrom.automation.testng.ListenerChain.onTestFailure(ListenerChain.java:395)
	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:66)
	at org.testng.internal.TestInvoker.runTestResultListener(TestInvoker.java:219)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:651)
	at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.testng.TestRunner.privateRun(TestRunner.java:766)
	at org.testng.TestRunner.run(TestRunner.java:587)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)_

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina/commit/5ecc29f63d8c0642b01025ce80019cf44d3ed9cd
