### ISSUE TITLE
Rerun failures sometimes is unstable in the carina 6.4.36

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/carina#1043]
1. Have run with some failures
2. Try to rerun from Zafira or jenkins.
-> Rerun was not started. 

dump log:
# Created at 2020-06-01T18:56:07.068
java.lang.ArrayIndexOutOfBoundsException: 0
    at com.qaprosoft.carina.core.foundation.listeners.TestNamingListener.setTestName(TestNamingListener.java:193)
    at com.qaprosoft.carina.core.foundation.listeners.TestNamingListener.getTestName(TestNamingListener.java:117)
    at com.qaprosoft.carina.core.foundation.report.ZafiraConfigurator.getTestName(ZafiraConfigurator.java:153)
    at com.qaprosoft.zafira.listener.ExcludeTestsForRerun.isTestNeedRerun(ExcludeTestsForRerun.java:159)
    at com.qaprosoft.zafira.listener.ExcludeTestsForRerun.excludeTestsForRerun(ExcludeTestsForRerun.java:85)
    at com.qaprosoft.zafira.listener.ZafiraEventRegistrar.onRunStart(ZafiraEventRegistrar.java:237)
    at com.qaprosoft.zafira.listener.ZebrunnerListener.onStart(ZebrunnerListener.java:79)
    at com.nordstrom.automation.testng.ListenerChain.onStart(ListenerChain.java:445)
    at org.testng.TestRunner.fireEvent(TestRunner.java:893)
    at org.testng.TestRunner.beforeRun(TestRunner.java:605)
    at org.testng.TestRunner.run(TestRunner.java:580)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
    at org.testng.SuiteRunner.run(SuiteRunner.java:286)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
    at org.testng.TestNG.runSuites(TestNG.java:1039)
    at org.testng.TestNG.run(TestNG.java:1007)
    at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
    at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
    at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
    at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

Possible error in 
int invCount = result.getTestContext().getAllTestMethods()[0].getInvocationCount();
        if (invCount > 1) {

**Comment by vdelendik** [comment]
hotfix can be teted with 6.4.846-SNAPSHOT core build

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/1044
