### ISSUE TITLE
think about removal of necessity to override several mandatory args

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1119]
For now there is no way to inject carina into any project without definding set of mandatory arguments
https://github.com/qaprosoft/carina/blob/master/carina-core/src/main/resources/config.properties
selenium_host={must_override}
report_url={must_override}
email_list={must_override}

and some not so evident properties like MAX_SCREENSHOOT_HISTORY
int maxHistory = Configuration.getInt(Parameter.MAX_SCREENSHOOT_HISTORY);

```
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at java.text.DateFormatSymbols.initializeData(DateFormatSymbols.java:693)
at java.text.DateFormatSymbols.<init>(DateFormatSymbols.java:145)
at sun.util.locale.provider.DateFormatSymbolsProviderImpl.getInstance(DateFormatSymbolsProviderImpl.java:85)
at java.text.DateFormatSymbols.getProviderInstance(DateFormatSymbols.java:364)
at java.text.DateFormatSymbols.getInstance(DateFormatSymbols.java:340)
at java.util.Calendar.getDisplayName(Calendar.java:2110)
at java.text.SimpleDateFormat.subFormat(SimpleDateFormat.java:1125)
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:966)
at java.text.SimpleDateFormat.format(SimpleDateFormat.java:936)
at java.text.DateFormat.format(DateFormat.java:345)
at org.apache.log4j.helpers.PatternParser$DatePatternConverter.convert(PatternParser.java:443)
at org.apache.log4j.helpers.PatternConverter.format(PatternConverter.java:65)
at org.apache.log4j.PatternLayout.format(PatternLayout.java:506)
at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:310)
at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
at org.apache.log4j.Category.callAppenders(Category.java:206)
at org.apache.log4j.Category.forcedLog(Category.java:391)
at org.apache.log4j.Category.warn(Category.java:1043)
at com.qaprosoft.carina.core.foundation.utils.PlaceholderResolver.resolve(PlaceholderResolver.java:63)
at com.qaprosoft.carina.core.foundation.utils.R.get(R.java:175)
at com.qaprosoft.carina.core.foundation.utils.Configuration.get(Configuration.java:294)
at com.qaprosoft.carina.core.foundation.utils.Configuration.getInt(Configuration.java:299)
at com.qaprosoft.carina.core.foundation.report.ReportContext.removeOldReports(ReportContext.java:526)
at com.qaprosoft.carina.core.foundation.report.ReportContext.getBaseDir(ReportContext.java:114)
at com.qaprosoft.carina.core.foundation.report.ReportContext.getTestDir(ReportContext.java:423)
at com.qaprosoft.carina.core.foundation.report.ReportContext.getTestDir(ReportContext.java:413)
at com.qaprosoft.carina.core.foundation.log.ThreadLogAppender.append(ThreadLogAppender.java:54)
at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66) (edited) 
```

**Comment by vdelendik** [comment]
fixed, confirmed on real use-case
