### ISSUE TITLE
Interaction with Web elements found by @FindBy(id="..") is not stable.

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/carina#1148]
**Describe the bug**
**Regression!**
Interaction with Web elements found by @FindBy(id="..") is not stable. 
Started from Carina 6.4.40 (not repro in 6.4.39)
The same element found by @FindBy(xpath="//*[@id='..']") works well. 
Checked with hover(), click(), check() methods. 
Interesting that this element can be found by isPresent() and isElementPresent()

After migration from 6.4.39 -> 6.4.40 (also checked on 6.4.41, 6.4.42 and 6.4.43) web elements (mostly react based) which were found in the following way : 
@FindBy(id="..")
private ExtendedWebElement element;

and calling command: 
element.hover();

leads for the following error: 

**Logs/Links**
```
Driver info: org.openqa.selenium.remote.RemoteWebDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 81.0, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20200917005511, moz:geckodriverVersion: 0.27.0, moz:headless: false, moz:processID: 68379, moz:profile: /var/folders/kf/lkk1d6ys32x..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: MAC, platformName: MAC, platformVersion: 19.6.0, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webdriver.remote.sessionid: 13b6be7a-4e5b-1549-bd9b-adb...}
Session ID: 13b6be7a-4e5b-1549-bd9b-adba7ac48a5a
*** Element info: {Using=id, value=larrow}
	at sun.reflect.GeneratedConstructorAccessor18.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringSeleniumCommandExecutor.execute(EventFiringSeleniumCommandExecutor.java:48)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:285)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:185)
	at org.openqa.selenium.remote.RemoteWebElement.findElementById(RemoteWebElement.java:221)
	at org.openqa.selenium.By$ById.findElement(By.java:188)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:181)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.lambda$new$0(EventFiringWebDriver.java:404)
	at com.sun.proxy.$Proxy23.findElement(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.findElement(EventFiringWebDriver.java:496)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:51)
	at com.sun.proxy.$Proxy19.findElement(Unknown Source)
	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.refindElement(ExtendedWebElement.java:382)
	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1404)
```

**Web (please complete the following information):**
 - Checked on chrome and firefox
 - Versions - different

**Additional context**

**Comment by maksimsarychau** [comment]
**Blocker**

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/1152
