### ISSUE TITLE
handle below exception in ProxyPool and write just single error message that "lsof" utility not found

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1175]
below you can find a stack trace from regular unit test compilation when "lsof" utility not installed.
`mvn -U clean eclipse:eclipse  compile install`

Please,  catch any ExecutorException and put in catch block simple error message. And only on debug full stacktrace with details.

```
2020-11-07 04:09:08 ProxyPool [main-1] [ERROR] Undefined failure during process kill by port number!
java.lang.RuntimeException: Cannot run program "lsof": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.utils.android.recorder.utils.AdbExecutor.execute(AdbExecutor.java:78)
	at com.qaprosoft.carina.browsermobproxy.ProxyPool.killProcessByPort(ProxyPool.java:353)
	at com.qaprosoft.carina.browsermobproxy.ProxyPool.startProxy(ProxyPool.java:210)
	at com.qaprosoft.carina.browsermobproxy.BrowserMobTest.testRegisterProxy(BrowserMobTest.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.testng.TestRunner.privateRun(TestRunner.java:764)
	at org.testng.TestRunner.run(TestRunner.java:585)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.runSuites(TestNG.java:1069)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
Caused by: com.qaprosoft.carina.core.foundation.utils.android.recorder.exception.ExecutorException: Cannot run program "lsof": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.utils.android.recorder.utils.ProcessBuilderExecutor.start(ProcessBuilderExecutor.java:93)
	at com.qaprosoft.carina.core.foundation.utils.android.recorder.utils.AdbExecutor.execute(AdbExecutor.java:66)
	... 36 more
Caused by: java.io.IOException: Cannot run program "lsof": CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.qaprosoft.carina.core.foundation.utils.android.recorder.utils.ProcessBuilderExecutor.start(ProcessBuilderExecutor.java:87)
	... 37 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:444)
	at java.lang.ProcessImpl.start(ProcessImpl.java:140)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 38 more
```

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina/commit/732e49fdb71def2732356a098d5b76cfb641ee6d

log is much bettr now:
```
2020-11-07 04:18:13 ProxyPool [main-1] [INFO] Starting BrowserMob proxy...
2020-11-07 04:18:13 ProxyPool [main-1] [INFO] Process on port 51767 will be closed.
2020-11-07 04:18:13 ProxyPool [main-1] [ERROR] Unable to kill process by lsof utility: Cannot run program "lsof": CreateProcess error=2, The system cannot find the file specified
2020-11-07 04:18:13 ProxyPool [main-1] [WARN] Set http/https proxy settings only to use with BrowserMobProxy host: 10.8.101.171; port: 51767
WARN! Value not resolved by key: no_proxy
```
