### ISSUE TITLE
NullPointerException in log appender

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1243]
```
21:58:55  java.lang.NullPointerException
21:58:55  	at com.qaprosoft.carina.core.foundation.log.ThreadLogAppender.append(ThreadLogAppender.java:80)
21:58:55  	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
21:58:55  	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
21:58:55  	at org.apache.log4j.Category.callAppenders(Category.java:206)
21:58:55  	at org.apache.log4j.Category.forcedLog(Category.java:391)
21:58:55  	at org.apache.log4j.Category.log(Category.java:856)
21:58:55  	at org.slf4j.impl.Log4jLoggerAdapter.error(Log4jLoggerAdapter.java:498)
21:58:55  	at ...
21:58:55  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
21:58:55  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
21:58:55  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
21:58:55  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
21:58:55  	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
21:58:55  	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
21:58:55  	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
21:58:55  	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
21:58:55  	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
21:58:55  	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
21:58:55  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
21:58:55  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
21:58:55  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:58:55  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:58:55  	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vdelendik** [comment]
fixed
