### ISSUE TITLE
adjust unit tests to make adb cases optional if adb not present in the path

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#1301]
```
[ERROR] com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.connectRemoteTest  Time elapsed: 0.011 s  <<< FAILURE!
java.lang.RuntimeException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.connectRemoteTest(DevicePoolTest.java:117)
Caused by: com.qaprosoft.carina.core.foundation.utils.android.recorder.exception.ExecutorException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.connectRemoteTest(DevicePoolTest.java:117)
Caused by: java.io.IOException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.connectRemoteTest(DevicePoolTest.java:117)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.connectRemoteTest(DevicePoolTest.java:117)

[ERROR] com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.disconnectRemoteTest  Time elapsed: 0.002 s  <<< FAILURE!
java.lang.RuntimeException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.disconnectRemoteTest(DevicePoolTest.java:125)
Caused by: com.qaprosoft.carina.core.foundation.utils.android.recorder.exception.ExecutorException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.disconnectRemoteTest(DevicePoolTest.java:125)
Caused by: java.io.IOException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.disconnectRemoteTest(DevicePoolTest.java:125)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.disconnectRemoteTest(DevicePoolTest.java:125)

[ERROR] com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.isAppUninstallTest  Time elapsed: 0.008 s  <<< FAILURE!
java.lang.RuntimeException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.isAppUninstallTest(DevicePoolTest.java:136)
Caused by: com.qaprosoft.carina.core.foundation.utils.android.recorder.exception.ExecutorException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.isAppUninstallTest(DevicePoolTest.java:136)
Caused by: java.io.IOException: Cannot run program "adb": CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.isAppUninstallTest(DevicePoolTest.java:136)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at com.qaprosoft.carina.core.foundation.webdriver.DevicePoolTest.isAppUninstallTest(DevicePoolTest.java:136)

```

**Comment by DenisPitsul2020** [comment]
Removed adb test, because not all machines which build the project have adb locally
https://github.com/qaprosoft/carina/pull/1305
