### ISSUE TITLE
improve screenshoting rules on failures disabling it for "Session timed out or not found"

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#318]
No sense to make screenshot if current driver has "Session timed out or not found" problem.
Maybe integrate error analysis inside DriverPool or similar

**Comment by vdelendik** [comment]
10:46:51 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test (default-test) on project ***: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.18:test failed: There was an error in the forked process
10:46:51 [ERROR] java.lang.RuntimeException: Operation not started: capture_screenshot
10:46:51 [ERROR] at com.qaprosoft.carina.core.foundation.performance.Timer.stop(Timer.java:44)
10:46:51 [ERROR] at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.capture(Screenshot.java:363)
10:46:51 [ERROR] at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.captureFullSize(Screenshot.java:185)
10:46:51 [ERROR] at com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener.takeScreenshot(AbstractTestListener.java:588)
10:46:51 [ERROR] at com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener.failItem(AbstractTestListener.java:82)
10:46:51 [ERROR] at com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener.onTestFailure(AbstractTestListener.java:322)
10:46:51 [ERROR] at org.testng.internal.Invoker.runTestListeners(Invoker.java:1895)
10:46:51 [ERROR] at org.testng.internal.Invoker.runTestListeners(Invoker.java:1879)
10:46:51 [ERROR] at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1292)
10:46:51 [ERROR] at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
10:46:51 [ERROR] at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
10:46:51 [ERROR] at org.testng.TestRunner.privateRun(TestRunner.java:767)
10:46:51 [ERROR] at org.testng.TestRunner.run(TestRunner.java:617)
10:46:51 [ERROR] at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
10:46:51 [ERROR] at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
10:46:51 [ERROR] at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
10:46:51 [ERROR] at org.testng.SuiteRunner.run(SuiteRunner.java:254)
10:46:51 [ERROR] at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
10:46:51 [ERROR] at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
10:46:51 [ERROR] at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
10:46:51 [ERROR] at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
10:46:51 [ERROR] at org.testng.TestNG.run(TestNG.java:1057)
10:46:51 [ERROR] at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
10:46:51 [ERROR] at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
10:46:51 [ERROR] at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
10:46:51 [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
10:46:51 [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
10:46:51 [ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by vdelendik** [comment]
it should be fixed in 5.2.3.96+
