### ISSUE TITLE
Hanging on isElementPresent

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#365]
environment
carina: 5.2.4.101
appium 1.8.1

Test starts
after some actions executed, test hangs on element.isElementPreset(timeout);

**Comment by Litsvin** [comment]
appium's logs:

[debug] [ADB] Running '/Users/akratovich/Library/Android/sdk/platform-tools/adb -P 5037 -s nerdwallet.qaprosoft.com\:7422 forward tcp\:4724 tcp\:4724'
[debug] [UiAutomator] Starting UiAutomator
[debug] [UiAutomator] Moving to state 'starting'
[debug] [UiAutomator] Parsing uiautomator jar
[debug] [UiAutomator] Found jar name: 'AppiumBootstrap.jar'
[debug] [ADB] Running '/Users/akratovich/Library/Android/sdk/platform-tools/adb -P 5037 -s nerdwallet.qaprosoft.com\:7422 push /usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/bootstrap/bin/AppiumBootstrap.jar /data/local/tmp/'
[debug] [ADB] Attempting to kill all uiautomator processes
[debug] [ADB] Getting all processes with uiautomator
[debug] [ADB] Running '/Users/akratovich/Library/Android/sdk/platform-tools/adb -P 5037 -s nerdwallet.qaprosoft.com\:7422 shell ps'
[ADB] No uiautomator process found to kill, continuing...
[debug] [UiAutomator] Starting UIAutomator
[debug] [ADB] Creating ADB subprocess with args: ["-P",5037,"-s","nerdwallet.qaprosoft.com:7422","shell","uiautomator","runtest","AppiumBootstrap.jar","-c","io.appium.android.bootstrap.Bootstrap","-e","pkg","com.mobilecreditcards","-e","disableAndroidWatchers",false,"-e","acceptSslCerts",false]
[UiAutomator] UiAutomator exited unexpectedly with code 0, signal null
[debug] [UiAutomator] Moving to state 'stopped'
Unhandled rejection Error: UiAUtomator shut down unexpectedly
    at AndroidBootstrap.callee$2$0$ (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/lib/bootstrap.js:177:42)
    at tryCatch (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:315:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:185:17)
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/appium/node_modules/core-js/library/modules/$.export.js:30:36)
    at AsyncIterator.enqueue (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:184:12)
    at AsyncIterator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at Object.runtime.async (/usr/local/lib/node_modules/appium/node_modules/babel-runtime/regenerator/runtime.js:209:12)
    at UiAutomator.callee$2$0 (/usr/local/lib/node_modules/appium/node_modules/appium-android-bootstrap/build/lib/bootstrap.js:357:42)
    at UiAutomator.emit (events.js:182:13)
    at UiAutomator.changeState (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator/lib/uiautomator.js:85:10)
    at SubProcess.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-uiautomator/lib/uiautomator.js:47:14)
    at SubProcess.emit (events.js:182:13)
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/teen_process/lib/subprocess.js:130:14)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
[HTTP] <-- POST /wd/hub/session - - ms - -
[HTTP]

**Comment by Litsvin** [comment]
if i add following capabilities (1st or 2nd):
 params.put("capabilities.appWaitDuration", "270000")
  params.put("capabilities.androidInstallTimeout", "270000")

then i see no error in appium logs.

logs from eclipse console:

2018-06-21 19:21:14 DriverListener [main] [ERROR] [SM-G950F] java.io.IOException: unexpected end of stream on Connection{localhost:4723, proxy=DIRECT hostAddress=localhost/127.0.0.1:4723 cipherSuite=none protocol=http/1.1}
Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
System info: host: 'akratovich-NW1465', ip: 'fe80:0:0:0:1850:104c:919b:5e0%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.5', java.version: '1.8.0_171'
Driver info: driver.version: EventFiringWebDriver

with no stack trace (it freezes)

logs from appium:
ndroid.view.View","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got data from client: {"cmd":"action","action":"find","params":{"strategy":"xpath","selector":"//*[@content-desc = 'scoreGaugeContainer']/android.view.View","context":"","multiple":false}}
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command of type ACTION
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Got command action: find
[debug] [AndroidBootstrap] [BOOTSTRAP LOG] [debug] Finding '//*[@content-desc = 'scoreGaugeContainer']/android.view.View' using 'XPATH' with the contextId: '' multiple: false
[HTTP] <-- POST /wd/hub/session/aeb1f6ef-ceb6-4305-8dbb-094a98941495/element - - ms - -
[HTTP] 
[HTTP] --> GET /wd/hub/session/aeb1f6ef-ceb6-4305-8dbb-094a98941495/screenshot
[HTTP] {}
[debug] [W3C] Calling AppiumDriver.getScreenshot() with args: ["aeb1f6ef-ceb6-4305-8dbb-094a98941495"]
[HTTP] <-- GET /wd/hub/session/aeb1f6ef-ceb6-4305-8dbb-094a98941495/screenshot - - ms - -
[HTTP]

**Comment by deNatallia** [comment]
fixed in direct
