### ISSUE TITLE
hub: remove problematic device from pool

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#445]
as only we find any problem with device/adb/install etc it should be removed from defaultPool on selenium-hub level.

Also ideall we have to notify admins that something is wrong with this device

10:47:22 java.lang.RuntimeException: org.openqa.selenium.WebDriverException: cannot create session QPS-HUB-* on any hosts after 1 attempt(s), last host error was: An unknown server-side error occurred while processing the command. Original error: Error finding if process exists. Original error: Error executing adbExec. Original error: 'Command '/opt/android-sdk-linux/platform-tools/adb -P 5037 -s 4d0000106f0a5063 shell ps' timed out after 20000ms'; Stderr: ''; Code: 'null' (WARNING: The server did not provide any stacktrace information)
10:47:22 Command duration or timeout: 120.46 seconds
10:47:22 Build info: version: '3.12.0', revision: '7c6e0b3', time: '2018-05-08T14:04:26.12Z'
10:47:22 System info: host: 'b649aafca980', ip: '172.21.0.16', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-134-generic', java.version: '1.8.0_151'
10:47:22 Driver info: driver.version: AndroidDriver
10:47:22 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
10:47:22 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
10:47:22 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
10:47:22 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
10:47:22 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
10:47:22 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
10:47:22 	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)
10:47:22 	at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)
10:47:22 	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
10:47:22 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
10:47:22 	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
10:47:22 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
10:47:22 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
10:47:22 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
10:47:22 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
10:47:22 	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
10:47:22 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
10:47:22 	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
10:47:22 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
10:47:22 	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
10:47:22 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
10:47:22 	at com.qaprosoft.carina.core.foundation.webdriver.listener.EventFiringAppiumCommandExecutor.execute(EventFiringAppiumCommandExecutor.java:151)
10:47:22 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
10:47:22 	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
10:47:22 	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
10:47:22 	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
10:47:22 	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
10:47:22 	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
10:47:22 	at io.appium.java_client.DefaultGenericMobileDriver.<init>(DefaultGenericMobileDriver.java:38)
10:47:22 	at io.appium.java_client.AppiumDriver.<init>(AppiumDriver.java:84)
10:47:22 	at io.appium.java_client.android.AndroidDriver.<init>(AndroidDriver.java:83)
10:47:22 	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.impl.MobileFactory.create(MobileFactory.java:115)
10:47:22 	at com.qaprosoft.carina.core.foundation.webdriver.core.factory.DriverFactory.create(DriverFactory.java:70)
10:47:22 	at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.createDriver(DriverPool.java:328)
10:47:22 	at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:146)
10:47:22 	at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:98)
10:47:22 	at com.qaprosoft.carina.core.foundation.webdriver.DriverPool.getDriver(DriverPool.java:67)
10:47:22 	at com.qaprosoft.carina.core.foundation.utils.factory.CustomTypePageFactory.initPage(CustomTypePageFactory.java:59)

**Comment by vdelendik** [comment]
after implementing this feature we can take a look to the current as well.

https://github.com/qaprosoft/carina/pull/640

**Comment by vdelendik** [comment]
we started investigation howto improve carina-grid (QPS-HUB) to make integration between carina and devices smarter: https://github.com/qaprosoft/carina/issues/184.
As only #184 is finished we can start with current one

**Comment by vdelendik** [comment]
closing as new one submitted in independent carina-grid project
