### ISSUE TITLE
Unwanted stack trace on element.getText()

### ISSUE THREAD

**Issue by Litsvin** [qaprosoft/carina#539]
carina-core version 5.3.3.128

2018-11-16 19:00:28 ExtendedWebElement [main-1] [ERROR] [SM-G950F] waitUntil: null (n/a)
java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:305)
	at io.appium.java_client.DefaultGenericMobileDriver.findElements(DefaultGenericMobileDriver.java:50)
	at io.appium.java_client.AppiumDriver.findElements(AppiumDriver.java:148)
	at org.openqa.selenium.support.ui.ExpectedConditions.findElement(ExpectedConditions.java:895)
	at org.openqa.selenium.support.ui.ExpectedConditions.access$000(ExpectedConditions.java:44)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:183)
	at org.openqa.selenium.support.ui.ExpectedConditions$6.apply(ExpectedConditions.java:180)
	at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1427)
	at org.openqa.selenium.support.ui.ExpectedConditions$47.apply(ExpectedConditions.java:1421)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:248)
	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.waitUntil(ExtendedWebElement.java:333)
	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1497)
	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1483)
	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.getText(ExtendedWebElement.java:455)

**Comment by vdelendik** [comment]
@Litsvin, do you have results with latest carina?

**Comment by Litsvin** [comment]
@vdelendik 
yes, with carina 6.0.9 everything is OK

**Comment by vdelendik** [comment]
done
