### ISSUE TITLE
hide "Can't save file to Amazon S3!" error message stack-trace

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#609]
in case of any zafira-amazon integration issues we have a lot of error messages in console logs:
08:00:33 2019-01-06 08:00:32 Screenshot [pool-8-thread-26-25] [ERROR] Can't save file to Amazon S3
08:00:33 java.lang.Exception: Can't save file to Amazon S3. Verify your credentials or bucket name
08:00:33 	at com.qaprosoft.zafira.client.ZafiraClient.uploadFile(ZafiraClient.java:1046)
08:00:33 	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.lambda$uploadToAmazonS3$0(Screenshot.java:402)
08:00:33 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:00:33 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:00:33 	at java.lang.Thread.run(Thread.java:748)

so let's move it to debug log level as we can't fix configuration steps on core or test level at all. if no screenshots on zafira it should be fixed by Zafira admin

**Comment by vdelendik** [comment]
6.0.6+
