### ISSUE TITLE
unable to load l18n packages for carina-demo

### ISSUE THREAD

**Issue by Nilesh61181** [qaprosoft/carina#711]
2019-05-06 20:53:42 CarinaListener [main] [ERROR] I18N bundle is not initialized successfully!
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at com.qaprosoft.carina.core.foundation.utils.resources.Resources.getResourceURLs(Resources.java:77)
	at com.qaprosoft.carina.core.foundation.utils.resources.I18N.init(I18N.java:56)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.<clinit>(CarinaListener.java:113)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
	at java.base/java.lang.Class.newInstance(Class.java:590)
	at org.testng.internal.ClassHelper.newInstance(ClassHelper.java:69)
	at org.testng.internal.DefaultListenerFactory.createListener(DefaultListenerFactory.java:13)
	at org.testng.TestRunner.initListeners(TestRunner.java:315)
	at org.testng.TestRunner.init(TestRunner.java:274)
	at org.testng.TestRunner.init(TestRunner.java:241)
	at org.testng.TestRunner.<init>(TestRunner.java:192)
	at org.testng.remote.support.RemoteTestNG6_12$1.newTestRunner(RemoteTestNG6_12.java:33)
	at org.testng.remote.support.RemoteTestNG6_12$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_12.java:66)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:713)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by kolyakrasnik** [comment]
@Nilesh61181 please, try with 6.1.470-SNAPSHOT.

**Comment by kolyakrasnik** [comment]
PR: https://github.com/qaprosoft/carina/pull/713

**Comment by vdelendik** [comment]
we expect that above PR should fix the issue.
Fix will be available in 6.1.20+ Carina version. Estimated release date: May-10
