### ISSUE TITLE
Clean up logs in debug mode

### ISSUE THREAD

**Issue by kolyakrasnik** [qaprosoft/carina#772]
**Describe the bug**
Currently we are getting unwanted exception in the logs in debug mode 
`01:15:30  java.io.IOException: No such file or directory
01:15:30  	at java.io.UnixFileSystem.createFileExclusively(Native Method)
01:15:30  	at java.io.File.createNewFile(File.java:1012)
01:15:30  	at com.qaprosoft.carina.core.foundation.log.ThreadLogAppender.append(ThreadLogAppender.java:56)
01:15:30  	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
01:15:30  	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
01:15:30  	at org.apache.log4j.Category.callAppenders(Category.java:206)`

**Comment by kolyakrasnik** [comment]
https://github.com/qaprosoft/carina/pull/773
