### ISSUE TITLE
Unable to publish screenshot artifacts right after renaming test folder

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#790]
6.1.25

16:01:03  2019-08-07 13:00:59 Messager [TestNG-PoolService-0-28] [INFO] INFO:  TEST [MYTESTNAME] STARTED at [13:00:59 2019-08-07]
16:01:03  [com.qaprosoft.zafira.client.impl.IntegrationClientImpl] ERROR - Can't save file to Amazon S3 
16:01:03  java.io.FileNotFoundException: /tmp/jenkins/workspace/.../regression-tests/../../reports/qa/1565182767773/e85c9d8f-b27f-4439-9694-8afacfca8e2c/thumbnails/1565182855227.png (No such file or directory)
16:01:03  	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_181]
16:01:03  	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_181]
16:01:03  	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_181]
16:01:03  	at com.qaprosoft.zafira.client.impl.IntegrationClientImpl.uploadFile(IntegrationClientImpl.java:79) ~[zafira-client-4.1.59.jar:na]
16:01:03  	at com.qaprosoft.zafira.client.impl.ZafiraClientImpl.uploadFile(ZafiraClientImpl.java:280) [zafira-client-4.1.59.jar:na]
16:01:03  	at com.qaprosoft.amazon.client.AmazonS3Client.lambda$upload$5(AmazonS3Client.java:73) [carina-aws-s3-6.1.25.jar:na]
16:01:03  	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[na:1.8.0_181]
16:01:03  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
16:01:03  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
16:01:03  	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
16:01:03  [com.qaprosoft.zafira.client.impl.IntegrationClientImpl] ERROR - Can't save file to Amazon S3 
16:01:03  java.io.FileNotFoundException: /tmp/jenkins/workspace/.../regression-tests/../../reports/qa/1565182767773/e85c9d8f-b27f-4439-9694-8afacfca8e2c/1565182855227.png (No such file or directory)
16:01:03  	at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_181]
16:01:03  	at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_181]
16:01:03  	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_181]
16:01:03  	at com.qaprosoft.zafira.client.impl.IntegrationClientImpl.uploadFile(IntegrationClientImpl.java:79) ~[zafira-client-4.1.59.jar:na]
16:01:03  	at com.qaprosoft.zafira.client.impl.ZafiraClientImpl.uploadFile(ZafiraClientImpl.java:280) [zafira-client-4.1.59.jar:na]
16:01:03  	at com.qaprosoft.amazon.client.AmazonS3Client.lambda$upload$5(AmazonS3Client.java:73) [carina-aws-s3-6.1.25.jar:na]
16:01:03  	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[na:1.8.0_181]
16:01:03  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
16:01:03  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
16:01:03  	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]

**Comment by vdelendik** [comment]
agreed to avoid testfolder renaming on carina level. Local report should be good using unique uuid values. For those who would like to gnerate specific folder in 6.1.24+ we provided public method to rename into the business related value

**Comment by vdelendik** [comment]
skip any test folders renaming for local reports at finish. at the same time keep in ReportContext class:
public synchronized static File setCustomTestDirName(String dirName)
Above method can be used on test layer to rename each test result diectory according to personal wishes. 
Globally it should finish all kind of problems when artifacts are pushing to AWS and removed/renamed at the same time
