### ISSUE TITLE
test run without Zafira integration has NoSuchElementException at the end

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#823]
Exception in thread "Thread-0" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Unknown Source)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener$ShutdownHook.quitAllDriversOnHook(CarinaListener.java:861)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener$ShutdownHook.run(CarinaListener.java:887)

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/commit/12418cf5aefde2ae6307083c61eac2cf026c3d9f
