### ISSUE TITLE
Handle JIRA# parsing via description

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#844]
08:30:16 2019-11-11 16:30:16 Jira [TestNG-tests-1-61] [ERROR] Incorrect Jira-ticket format: JIRA#
08:30:16 java.lang.ArrayIndexOutOfBoundsException: 1
08:30:16 	at com.qaprosoft.carina.core.foundation.jira.Jira.getTickets(Jira.java:121)
08:30:16 	at com.qaprosoft.carina.core.foundation.report.ZafiraConfigurator.getTestWorkItems(ZafiraConfigurator.java:162)
08:30:16 	at com.qaprosoft.zafira.listener.ZafiraEventRegistrar.onTestStart(ZafiraEventRegistrar.java:264)
08:30:16 	at com.qaprosoft.zafira.listener.ZafiraListener.onTestStart(ZafiraListener.java:57)
08:30:16 	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:73)
08:30:16 	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
08:30:16 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:559)
08:30:16 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
08:30:16 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
08:30:16 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
08:30:16 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
08:30:16 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
08:30:16 	at org.testng.TestRunner.run(TestRunner.java:505)
08:30:16 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
08:30:16 	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
08:30:16 	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
08:30:16 	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
08:30:16 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
08:30:16 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
08:30:16 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
08:30:16 	at java.lang.Thread.run(Thread.java:748)

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/852
