### ISSUE TITLE
jira integration failure break listeners logic

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#848]
17:51:04  2019-11-14 14:50:54 Jira [main-1] [ERROR] Exception during retrieving bug info
17:51:04  net.rcarz.jiraclient.JiraException: Failed to retrieve issue PF-9592
17:51:04  	at net.rcarz.jiraclient.Issue.realGet(Issue.java:700)
17:51:04  	at net.rcarz.jiraclient.Issue.get(Issue.java:723)
17:51:04  	at net.rcarz.jiraclient.JiraClient.getIssue(JiraClient.java:90)
17:51:04  	at com.qaprosoft.carina.core.foundation.jira.Jira.processBug(Jira.java:186)
17:51:04  	at com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener.createTestResult(AbstractTestListener.java:544)
17:51:04  	at com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener.failItem(AbstractTestListener.java:96)
17:51:04  	at com.qaprosoft.carina.core.foundation.listeners.AbstractTestListener.onTestFailure(AbstractTestListener.java:344)
17:51:04  	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onTestFailure(CarinaListener.java:293)
17:51:04  	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
17:51:04  	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
17:51:04  	at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
17:51:04  	at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
17:51:04  	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
17:51:04  	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
17:51:04  	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
17:51:04  	at org.testng.TestRunner.privateRun(TestRunner.java:648)
17:51:04  	at org.testng.TestRunner.run(TestRunner.java:505)
17:51:04  	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
17:51:04  	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
17:51:04  	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
17:51:04  	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
17:51:04  	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
17:51:04  	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
17:51:04  	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
17:51:04  	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
17:51:04  	at org.testng.TestNG.runSuites(TestNG.java:1049)
17:51:04  	at org.testng.TestNG.run(TestNG.java:1017)
17:51:04  	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
17:51:04  	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
17:51:04  	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
17:51:04  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
17:51:04  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
17:51:04  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
17:51:04  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by vdelendik** [comment]
let's log in debug mode error and stacktrace. For regular runtime just keep:
LOG.error("Exception during retrieving bug info: ", e.getMessage());

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/pull/855
