### ISSUE TITLE
ClassCastException for the browserstack sessions on iPhone (mobile+web)

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#903]
02:27:10 2020-01-30 10:27:08 ExtendedWebElement [TestNG-tests-1-22] [ERROR] [iPhone XS Max] FAIL: type - waitCondition for element 'fieldName (By.xpath: //div[contains(@class, 'visible')]//input[@name='name'])' not satisfied!
02:27:10 2020-01-30 10:27:08 ExtendedWebElement [TestNG-tests-1-22] [ERROR] [iPhone XS Max] catched WebDriverException: 
02:27:10 org.openqa.selenium.NoSuchElementException: An element could not be located on the page using the given search parameters. (WARNING: The server did not provide any stacktrace information)
02:27:10 Command duration or timeout: 0 milliseconds
02:27:10 For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
02:27:10 Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
02:27:10 System info: host: 'uw2-adhoc-instance-demo-default-nprd-513aeb', ip: '10.81.58.235', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-957.5.1.el7.x86_64', java.version: '1.8.0_172'
02:27:10 Driver info: org.openqa.selenium.remote.RemoteWebDriver
02:27:10 Capabilities {64bit: false, STF_ENABLED: false, acceptSslCert: false, acceptSslCerts: false, appium_port: 8084, automationName: XCUITest, bootstrapPath: /usr/local/.browserstack/co..., browser: iphone, browserName: safari, browser_name: iPhone, browserstack-tunnel: true, browserstack.appiumLogs: true, browserstack.debug: false, browserstack.finalTunnelFork: carinaTestRunId: 8451ef7d-1b81-40de-a798-7eb..., databaseEnabled: false, detected_language: selenium/3.141.59 (java unix), device: iphone, deviceName: iPhone XS Max, deviceOrientation: portrait, enableVNC: true, enableVideo: true, javascriptEnabled: true, locationContextEnabled: false, mobile: {browser: mobile, version: iPhone XS Max-12.1}, networkConnectionEnabled: false, newCommandTimeout: 300, noReset: true, orientation: PORTRAIT, orig_os: ios, os_version: , platform: MAC, platformName: MAC, platformVersion: 12.1, proxy_type: privoxy, realMobile: true, real_mobile: true, safariIgnoreFraudWarning: true, safariInitialUrl: http://mobile-internet-chec..., takesScreenshot: true, udid: 00008020-001A3C1A2608002E, useXctestrunFile: true, version: , wda_port: 8404, webStorageEnabled: false, webkitResponseTimeout: 20000}
02:27:10 Session ID: 50d779a5bcf7925b3b5aa96c0d6637ebaa629f45
02:27:10 *** Element info: {Using=xpath, value=//div[contains(@class, 'visible')]//input[@name='name']}
02:27:10 	at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
02:27:10 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
02:27:10 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
02:27:10 	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
02:27:10 	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
02:27:10 	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
02:27:10 	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
02:27:10 	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
02:27:10 	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
02:27:10 	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
02:27:10 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
02:27:10 	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
02:27:10 	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
02:27:10 	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
02:27:10 	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
02:27:10 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:27:10 	at java.lang.reflect.Method.invoke(Method.java:498)
02:27:10 	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
02:27:10 	at com.sun.proxy.$Proxy22.findElement(Unknown Source)
02:27:10 	at org.openqa.selenium.support.events.EventFiringWebDriver.findElement(EventFiringWebDriver.java:194)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.locator.ExtendedElementLocator.findElement(ExtendedElementLocator.java:111)
02:27:10 	at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
02:27:10 	at com.sun.proxy.$Proxy25.clear(Unknown Source)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement$1.doType(ExtendedWebElement.java:1488)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.executeAction(ExtendedWebElement.java:1293)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.overrideAction(ExtendedWebElement.java:1408)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.doAction(ExtendedWebElement.java:1377)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.type(ExtendedWebElement.java:661)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.type(ExtendedWebElement.java:649)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.decorator.ExtendedWebElement.type(ExtendedWebElement.java:639)
02:27:10 	at 
...
02:27:10 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
02:27:10 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
02:27:10 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:27:10 	at java.lang.reflect.Method.invoke(Method.java:498)
02:27:10 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
02:27:10 	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
02:27:10 	at com.qaprosoft.zafira.listener.ZafiraListener.lambda$run$0(ZafiraListener.java:103)
02:27:10 	at com.qaprosoft.zafira.listener.ZafiraEventRegistrar.onTestHook(ZafiraEventRegistrar.java:351)
02:27:10 	at com.qaprosoft.zafira.listener.ZafiraListener.run(ZafiraListener.java:103)
02:27:10 	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
02:27:10 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
02:27:10 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
02:27:10 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
02:27:10 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:27:10 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
02:27:10 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
02:27:10 	at org.testng.TestRunner.run(TestRunner.java:505)
02:27:10 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
02:27:10 	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
02:27:10 	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
02:27:10 	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
02:27:10 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:27:10 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:27:10 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:27:10 	at java.lang.Thread.run(Thread.java:748)
02:27:10 2020-01-30 10:27:09 Screenshot [TestNG-tests-1-22] [ERROR] [iPhone XS Max] Unable to capture screenshot due to the Exception!
02:27:10 java.lang.ClassCastException: org.openqa.selenium.remote.RemoteWebDriver cannot be cast to org.openqa.selenium.support.events.EventFiringWebDriver
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.takeFullScreenshot(Screenshot.java:579)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.capture(Screenshot.java:436)
02:27:10 	at com.qaprosoft.carina.core.foundation.webdriver.Screenshot.captureFailure(Screenshot.java:165)
02:27:10 	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.takeScreenshot(CarinaListener.java:858)
02:27:10 	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onTestFailure(CarinaListener.java:327)
02:27:10 	at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:67)
02:27:10 	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
02:27:10 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
02:27:10 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
02:27:10 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
02:27:10 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
02:27:10 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
02:27:10 	at org.testng.TestRunner.privateRun(TestRunner.java:648)
02:27:10 	at org.testng.TestRunner.run(TestRunner.java:505)
02:27:10 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
02:27:10 	at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
02:27:10 	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
02:27:10 	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
02:27:10 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:27:10 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02:27:10 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02:27:10 	at java.lang.Thread.run(Thread.java:748)

**Comment by vdelendik** [comment]
6.3.31+
