### ISSUE TITLE
AndroidService driver cast exception

### ISSUE THREAD

**Issue by dkline-920** [qaprosoft/carina#944]
**Describe the bug**
In Androidservice, need to use a castdriver when trying to open the notifications:
    public boolean findExpectedNotification(String expectedTitle, String expectedText, boolean partially) {
        // open notification
        try {
            ((AndroidDriver) getDriver()).openNotifications();

**Logs/Links**
2020-03-23 08:37:38 AndroidService [main-1] [ERROR] [SM-T720] org.openqa.selenium.support.events.EventFiringWebDriver cannot be cast to io.appium.java_client.android.AndroidDriver
java.lang.ClassCastException: org.openqa.selenium.support.events.EventFiringWebDriver cannot be cast to io.appium.java_client.android.AndroidDriver
	at com.qaprosoft.carina.core.foundation.utils.android.AndroidService.findExpectedNotification(AndroidService.java:439)
	at com.qaprosoft.carina.core.foundation.utils.android.AndroidService.findExpectedNotification(AndroidService.java:424)
	at com.hcl.nomad_qa.mobile.AndroidNotification2.testAndroidRunning(AndroidNotification2.java:40)

**Web (please complete the following information):**

**Mobile (please complete the following information):**
 - Device: Samsung Galaxy Tab S5e
 - OS: 9
 - Appium version  1.15.1

**Additional context**

**Comment by vdelendik** [comment]
https://github.com/qaprosoft/carina/commit/45d2eeed4d161ea4c0807b0ec48ca7d0868fbd15

fix should be available in
6.4.34-SNAPSHOT and 6.4.34+ core versions
