### ISSUE TITLE
we don't stop tests execution when custom_capabilities file is not detected

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#963]
**Describe the bug**
We shouldn't proceed with testing when custom capabilities file not found

**Logs/Links**
2020-04-05 21:45:09 CapabilitiesLoader [main-1] [INFO] Loading capabilities to global context from browserstack/osx/sierra_FireFox.properties
2020-04-05 21:45:09 CarinaListener [main-1] [ERROR] Undefined failure during static carina listener init!
java.lang.RuntimeException: Unable to find custom capabilities file 'browserstack/osx/sierra_FireFox.properties'!
	at com.qaprosoft.carina.core.foundation.webdriver.core.capability.CapabilitiesLoader.loadProperties(CapabilitiesLoader.java:124)
	at com.qaprosoft.carina.core.foundation.webdriver.core.capability.CapabilitiesLoader.loadCapabilities(CapabilitiesLoader.java:60)
	at com.qaprosoft.carina.core.foundation.webdriver.core.capability.CapabilitiesLoader.loadCapabilities(CapabilitiesLoader.java:46)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.<clinit>(CarinaListener.java:142)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.testng.internal.InstanceCreator.newInstance(InstanceCreator.java:30)
	at org.testng.internal.DefaultListenerFactory.createListener(DefaultListenerFactory.java:13)
	at org.testng.TestRunner.initListeners(TestRunner.java:384)
	at org.testng.TestRunner.init(TestRunner.java:341)
	at org.testng.TestRunner.init(TestRunner.java:291)
	at org.testng.TestRunner.<init>(TestRunner.java:179)
	at org.testng.SuiteRunner$DefaultTestRunnerFactory.newTestRunner(SuiteRunner.java:613)
	at org.testng.SuiteRunner.init(SuiteRunner.java:178)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:112)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1275)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1251)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1100)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by vdelendik** [comment]
throw new RuntimeException("Unable to find custom capabilities file '" + fileName + "'!");

but it doesn't stop tests execution!

**Comment by okamara** [comment]
Tested via overrideFields: carina-core_version=6.4.37-SNAPSHOT,custom_capabilities=my-caps.properties, Fixed.
<img width="1077" alt="Screen Shot 2020-06-11 at 2 07 00 PM" src="https://user-images.githubusercontent.com/32964663/84378474-e6246d80-abec-11ea-9b0f-c524c059cabc.png">
