### ISSUE TITLE
Unable to parse tesng attribute (jre 1.8.251)

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina#997]
java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.getAttributeValue(CarinaListener.java:831)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.setThreadCount(CarinaListener.java:877)
	at com.qaprosoft.carina.core.foundation.listeners.CarinaListener.onStart(CarinaListener.java:205)
	at com...automation.testng.ListenerChain.onStart(ListenerChain.java:211)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:223)
	at org.testng.SuiteRunner.run(SuiteRunner.java:284)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
	at org.testng.TestNG.runSuites(TestNG.java:1039)
	at org.testng.TestNG.run(TestNG.java:1007)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
2020-04-27 13:02:42 com.qaprosoft.zafira.listener.ZafiraEventRegistrar$TestRunShutdownHook [Thread-3] [INFO]: TestRunShutdownHook was executed with result: true

**Comment by vdelendik** [comment]
fixed
